### ISSUE TITLE
Failure reading LMK200BMW (aka LG K22) partitions

### ISSUE THREAD

**Issue by mike309game** [steadfasterX/lglaf#10]
Using the default branch can't list the partitions, but the develop branch can. Attempting to dump a partition using partitions.py results in the following error:
```
[arch@archlinux lglafng]$ python partitions.py --dump boot_a.img boot_a --debug
2021-11-07 22:44:27,229 LGLAF.py: DEBUG: product id in CR list: ><
2021-11-07 22:44:27,229 LGLAF.py: DEBUG: Final CR detection: None / 0
2021-11-07 22:44:27,230 LGLAF.py: DEBUG: Using endpoints 83 (IN), 02 (OUT)
2021-11-07 22:44:27,230 LGLAF.py: DEBUG: BASE_PROTOCOL_VERSION: 1000001
2021-11-07 22:44:27,231 LGLAF.py: DEBUG: DEV_PROTOCOL_VERSION: 1000001
2021-11-07 22:44:27,235 LGLAF.py: DEBUG: Switching to minimum version reported by lafd
2021-11-07 22:44:27,235 LGLAF.py: DEBUG: Negotiation in-use
2021-11-07 22:44:27,235 LGLAF.py: DEBUG: BASE_PROTOCOL_VERSION: 1000001
2021-11-07 22:44:27,236 LGLAF.py: DEBUG: DEV_PROTOCOL_VERSION: 1000008
2021-11-07 22:44:27,236 LGLAF.py: DEBUG: Switching protocol to 1000008
2021-11-07 22:44:27,279 LGLAF.py: DEBUG: Switching to minimum version reported by lafd
2021-11-07 22:44:27,279 LGLAF.py: DEBUG: Negotiation in-use
2021-11-07 22:44:27,280 partitions: DEBUG: Negotiated protocol version: 0x1000008
2021-11-07 22:44:27,283 LGLAF.py: DEBUG: using timeout value of: 2000
2021-11-07 22:44:27,296 LGLAF.py: DEBUG: Challenge: b'e8d0b55f'
2021-11-07 22:44:27,364 LGLAF.py: DEBUG: Response: b'e4df9b5a781d53b5e68f64f99a8f1a7c'
2021-11-07 22:44:27,365 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,367 LGLAF.py: DEBUG: KILO METR Response -> Header: b'4b494c4f4d455452000000000200000000000000000000002f5d0000b4b6b3b0', Body: b''
2021-11-07 22:44:27,371 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,375 partitions: DEBUG: opened a disk_fd: 58 on default
2021-11-07 22:44:27,375 partitions: DEBUG: check_block_size, read_offset: 0, end_offset: 24576, GPT_LBA_LEN: 6, BLOCK_SIZE: 4096, MAX_BLOCK_SIZE: 3
2021-11-07 22:44:27,375 partitions: DEBUG: Protocol based handling: 1000008
2021-11-07 22:44:27,379 LGLAF.py: DEBUG: using timeout value of: 3000
2021-11-07 22:44:27,387 partitions: DEBUG: No GPT header found for block size: 4096
2021-11-07 22:44:27,387 partitions: DEBUG: check_block_size, read_offset: 0, end_offset: 17408, GPT_LBA_LEN: 34, BLOCK_SIZE: 512, MAX_BLOCK_SIZE: 31
2021-11-07 22:44:27,387 partitions: DEBUG: Protocol based handling: 1000008
2021-11-07 22:44:27,390 LGLAF.py: DEBUG: using timeout value of: 3000
2021-11-07 22:44:27,418 partitions: DEBUG: GPT HEADER FOUND for block size: 512
2021-11-07 22:44:27,418 partitions: DEBUG: GPT_LBA_LEN: 34
2021-11-07 22:44:27,419 partitions: DEBUG: BLOCK_SIZE: 512 (EMMC), MAX_BLOCK_SIZE: 31
2021-11-07 22:44:27,419 partitions: DEBUG: Protocol based handling: 1000008
2021-11-07 22:44:27,422 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,438 LGLAF.py: DEBUG: using timeout value of: 2000
2021-11-07 22:44:27,442 LGLAF.py: DEBUG: Challenge: b'01205e1b'
2021-11-07 22:44:27,442 LGLAF.py: DEBUG: Response: b'8d9884296a2d584902b4b293b31f554e'
2021-11-07 22:44:27,445 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,449 LGLAF.py: DEBUG: KILO METR Response -> Header: b'4b494c4f4d45545200000000040000000000000000000000f98e0000b4b6b3b0', Body: b''
2021-11-07 22:44:27,453 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,456 partitions: DEBUG: Found partition on device: default
2021-11-07 22:44:27,457 partitions: DEBUG: part offset: 369098752, size: 67108864
2021-11-07 22:44:27,457 partitions: DEBUG: opener: b'\x00'
2021-11-07 22:44:27,460 LGLAF.py: DEBUG: using timeout value of: 2000
2021-11-07 22:44:27,464 LGLAF.py: DEBUG: Challenge: b'7bd3ae02'
2021-11-07 22:44:27,465 LGLAF.py: DEBUG: Response: b'9057545b38dfc2fc52e57416aa9d7a6d'
2021-11-07 22:44:27,468 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,472 LGLAF.py: DEBUG: KILO METR Response -> Header: b'4b494c4f4d455452000000000200000000000000000000002f5d0000b4b6b3b0', Body: b''
2021-11-07 22:44:27,477 LGLAF.py: DEBUG: using timeout value of: None
2021-11-07 22:44:27,480 partitions: DEBUG: opened a disk_fd: 58 on default
2021-11-07 22:44:27,485 partitions: DEBUG: Will read 67108864 bytes at disk offset 369098752
2021-11-07 22:44:27,488 LGLAF.py: DEBUG: using timeout value of: None
Traceback (most recent call last):
  File "/home/arch/programs/lglafng/partitions.py", line 752, in <module>
    main()
  File "/home/arch/programs/lglafng/partitions.py", line 732, in main
    dump_partition(comm, disk_fd, args.dump, part_offset, part_size, args.batch)
  File "/home/arch/programs/lglafng/partitions.py", line 344, in dump_partition
    data, disk_fd = laf_read(comm, disk_fd, read_offset // BLOCK_SIZE, chunksize)
  File "/home/arch/programs/lglafng/partitions.py", line 141, in laf_read
    header, response = comm.call(read_cmd, timeout=timeout)
  File "/home/arch/programs/lglafng/lglaf.py", line 349, in call
    raise RuntimeError('Command failed with error code %#x (%s)' % (errCode, msg))
RuntimeError: Command failed with error code 0x80000119 (LAF_ERROR_<unknown>)
```
This model appears to have only been released in Brazil (which is where I live) and Panama (under the model LMK200HMW) and information regarding its firmware is scarce, apart from LG not releasing any technical information asides from the modified Android kernel source.

**Comment by steadfasterX** [comment]
should be solved afaik, feel free to open a new issue or re-open if needed
